### ISSUE TITLE
Abandonado?

### ISSUE THREAD

**Issue by AlissonSteffens** [rbonichon/portugol#5]
O site está fora do ar :/
O projeto ainda está em desenvolvimento??

**Comment by rbonichon** [comment]
Eu tinha esquecido de atualizer o URL do site quand eu mudei o meu nome github. Eu corrigi o `README`.

Já que eu não estou mais no Brasil, eu não tenho mais o tempo para desenvolver o interpretador.

**Comment by AlissonSteffens** [comment]
Ok, Obrigado mesmo assim
